falcon_url: 'http://127.0.0.1:1988/v1/push'
metric: 'cloud2falcon'
step: 60
period: 13
cloud:
### aws mi_cloud
  - c_type: AWS
    resource: S3
    name: 'BucketName'
    to_falcon_template: 'aws-s3'
    ak: 'access key'
    sk: 'secret key'
    region: [{"name": 'ap-southeast-1', "site": 'sgpaws'}]
    metric_list: ['BucketSizeBytes','NumberOfObjects']
